version: "3"

services:
  fubot-dev:
    build: .
    image: fubot${ENVIRONMENT}
    container_name: fubot-${ENVIRONMENT}
    ports:
    - ${PORT_MAPPING} # not actually used as Karlish first needs to open ports on firewall
    restart: unless-stopped
    environment:
    - TEST_GUILD_ID=914185528268689428
    - LOGLEVEL=${LOGLEVEL}
    - DISCORDTOKEN=${DISCORDTOKEN}
    - CENSUS_TOKEN=${CENSUS_TOKEN}

  mongodb:
    image: mongo:5
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=FUBot
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: unless-stopped