version: "3"

services:
  fubot-dev:
    build: .
    image: fubot${ENVIRONMENT}
    container_name: fubot-${ENVIRONMENT}
    ports:
    - ${PORT_MAPPING} # not actually used as Karlish first needs to open ports on firewall
    restart: unless-stopped
    environment:
    - TEST_GUILD_ID=914185528268689428
    - LOGLEVEL=${LOGLEVEL}
    - DISCORDTOKEN=${DISCORDTOKEN}
    - CENSUS_TOKEN=${CENSUS_TOKEN}
    - MONGO_USERNAME=${MONGO_USERNAME}
    - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5
    container_name: mongodb
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: unless-stopped
