name: Development FUBot

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      LOGLEVEL: "DEBUG"
      DISCORDTOKEN: ${{ secrets.DISCORDTOKEN_DEV }}
      CENSUS_TOKEN: ${{ secrets.CENSUS_TOKEN }}
      ENVIRONMENT: "dev"
      PORT_MAPPING: 80:443
      MONGO_DB_PORT_MAPPING: "127.0.0.1:27017:27017"
      MONGO_DATA_DIR: "/var/lib/FUBot/mongodb"
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    steps:
      - uses: actions/checkout@v3

      - name: build images
        run: docker compose -f docker-compose-dev.yml build

      - name: update containers
        run: docker compose -f docker-compose-dev.yml up -d --force-recreate
