name: Production FUBot

# Controls when the workflow will run
on:
  push:
  # Triggers the workflow on push or pull request events but only for the "master" branch
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Create env vars for use by the build steps from GitHub secrets
    env:
      LOGLEVEL: "WARNING"
      DISCORDTOKEN: ${{ secrets.DISCORDTOKEN }}
      CENSUS_TOKEN: ${{ secrets.CENSUS_TOKEN }}
      ENVIRONMENT: "prod"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: build images
        run: docker compose build

        # update to latest container:
      - name: update containers
        run: docker compose up -d --force-recreate
