name: Docker Image CI

# Controls when the workflow will run
on:
  push:
  pull_request:
  # Triggers the workflow on push or pull request events but only for the "master" branch
    branches: [ "deployment","master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request_review:

    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted #[self-hosted, production]
    # Create env vars for use by the build steps referencing GitHub secrets
    env:
      DISCORDTOKEN: ${{ secrets.DISCORDTOKEN }}
      CENSUS_TOKEN: ${{ secrets.CENSUS_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: build bot image

        #  -f to make sure it rebuilds, --pull to make sure that built from the latest container
        run: docker compose build
        # update to latest container:
      - name: update containers
        run: docker compose up -d --force-recreate
