name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ "develop", "deployment" ]
  workflow_dispatch:
  pull_request_review:

jobs:
  build:
    runs-on: self-hosted
    env:
      LOGLEVEL: "DEBUG"
      DISCORDTOKEN: ${{ secrets.DISCORDTOKEN }}
      CENSUS_TOKEN: ${{ secrets.CENSUS_TOKEN }}
      GUILD_ID: ${{ secrets.GUILD_ID_DEV }}
      ENVIRONMENT: "dev"
    steps:
      - uses: actions/checkout@v3

      - name: build bot image
        run: docker compose build

      - name: update containers
        run: docker compose up -d --force-recreate
