name: Development FUBot

on:
  push:
  pull_request:
    branches: [ "develop", "deployment" ]
  workflow_dispatch:
  pull_request_review:

jobs:
  build:
    runs-on: self-hosted
    env:
      LOGLEVEL: "DEBUG"
      DISCORDTOKEN: ${{ secrets.DISCORDTOKEN }}
      CENSUS_TOKEN: ${{ secrets.CENSUS_TOKEN }}
      ENVIRONMENT: "dev"
    steps:
      - uses: actions/checkout@v3

      - name: build images
        run: docker compose -f docker-compose-dev.yml build

      - name: update containers
        run: docker compose -f docker-compose-dev.yml up -d --force-recreate
