name: Development FUBot

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      LOGLEVEL: INFO
      DISCORDTOKEN: ${{ secrets.DISCORDTOKEN_DEV }}
      CENSUS_TOKEN: ${{ secrets.CENSUS_TOKEN }}
      ENVIRONMENT: "dev"
      PORT_MAPPING: 80:443
      MONGO_DATA_DIR: /var/lib/FUBot-dev/mongodb
      MONGO_ADDRESS: mongodb-dev
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      ARMA_DB_HOST: ${{ secrets.ARMA_DB_HOST }}
      ARMA_DB_TOKEN: ${{ secrets.ARMA_DB_TOKEN }}
      ARMA_HOST: ${{ secrets.ARMA_HOST }}
      ARMA_QUERY_PORT: ${{ secrets.ARMA_QUERY_PORT }}
      ARMA_SFTP_HOST: ${{ secrets.ARMA_SFTP_HOST }}
      ARMA_SFTP_PORT: ${{ secrets.ARMA_SFTP_PORT }}
      ARMA_SFTP_USERNAME: ${{ secrets.ARMA_SFTP_USERNAME }}
      ARMA_SFTP_PASSWORD: ${{ secrets.ARMA_SFTP_PASSWORD }}
      ARMA_SFTP_MAP_PATH: ${{ secrets.ARMA_SFTP_MAP_PATH }}
    steps:
      - uses: actions/checkout@v3

      - name: build images
        run: docker compose -f docker-compose-dev.yml build

      - name: update containers
        run: docker compose -f docker-compose-dev.yml up -d --force-recreate