name: Upgrade chartbrew

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: chartbrew
    steps:
      - uses: actions/checkout@v3

      - name: Build chartbrew
        env:
          CB_HOSTNAME: ${{ secrets.CB_HOSTNAME }}
          CB_API_HOSTNAME: ${{ secrets.CB_API_HOSTNAME }}
          CB_DB_PASSWORD: ${{ secrets.CB_DB_PASSWORD }}
          CB_SECRET: ${{ secrets.CB_SECRET }}
        run: docker compose -f chartbrew-compose.yml down -d --force-recreate --pull always
